name: Workflow for flourish design system
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3

        - name: Install dependencies
          run: npm install

        - name: Build
          run: npm run build
  
  deploy-flourish-rapid:
    runs-on: ubuntu-latest
    steps:
      - uses: South-Paw/action-netlify-deploy@v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: './apps/flourish-rapid/dist'
          