name: Workflow for flourish design system
on: [push]
jobs:
  prepare-flourish-rapid:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3

        - name: Install dependencies
          run: npm install

        - name: Build
          run: npm run build

        - name: Deploy flourish-rapid
          uses: South-Paw/action-netlify-deploy@v1.2.0
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            netlify-auth-token: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
            netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
            build-dir: './apps/flourish-rapid/dist'
  integration-tests: 
    needs: prepare-flourish-rapid
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm install
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests against flourish-ui
      run: npm run run-playwright-tests
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: ./apps/flourish-integration-tests/playwright-report
        retention-days: 3
  publish-flourish-tokens:
    needs: integration-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: "https://registry.npmjs.org/"
      - name: Check if flourish-tokens version has been updated
        id: check
        uses: EndBug/version-check@v2
        with:
          file-name: ./packages/flourish-tokens/package.json
      - name: Publish flourish-tokens 
        # run only if a new release was created
        if: steps.check.outputs.changed == 'true'
        working-directory: ./packages/flourish-tokens
        run: npm publish --access public
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
  publish-flourish-ui:
    needs: publish-flourish-tokens
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: "https://registry.npmjs.org/"
      - name: Check if flourish-ui version has been updated
        id: check
        uses: EndBug/version-check@v2
        with:
          file-name: ./packages/flourish-ui/package.json
      - name: Publish flourish-ui
        # run only if a new release was created
        if: steps.check.outputs.changed == 'true'
        working-directory: ./packages/flourish-ui
        run: npm publish --access public
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}


        
