name: Workflow for flourish design system
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3

        - name: Install dependencies
          run: npm install

        - name: Build
          run: npm run build

        - name: Deploy flourish-rapid
          uses: South-Paw/action-netlify-deploy@v1.2.0
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            netlify-auth-token: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
            netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
            build-dir: './apps/flourish-rapid/dist'
          